import { Level, Item } from './types';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 'ch1_self_intro',
    name: 'CHAPTER 1: SELF INTRO',
    icon: 'UserCircle',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'わたし', kanji: '私', indonesian: 'SAYA', romaji: 'watashi' },
      { japanese: 'あなた', indonesian: 'ANDA', romaji: 'anata' },
      { japanese: 'かぞく', kanji: '家族', indonesian: 'KELUARGA', romaji: 'kazoku' },
      { japanese: 'おはよう', indonesian: 'SELAMAT PAGI', romaji: 'ohayou' },
      { japanese: 'くに', kanji: '国', indonesian: 'NEGARA', romaji: 'kuni' },
      { japanese: 'なまえ', kanji: '名前', indonesian: 'NAMA', romaji: 'namae' },
      { japanese: 'だれ', kanji: '誰', indonesian: 'SIAPA', romaji: 'dare' },
      { japanese: 'なに', kanji: '何', indonesian: 'APA', romaji: 'nani' },
      { japanese: 'はい', indonesian: 'IYA', romaji: 'hai' },
      { japanese: 'いいえ', indonesian: 'TIDAK', romaji: 'iie' },
      { japanese: 'せんせい', kanji: '先生', indonesian: 'GURU', romaji: 'sensei' },
      { japanese: 'がくせい', kanji: '学生', indonesian: 'SISWA', romaji: 'gakusei' },
      { japanese: 'いしゃ', kanji: '医者', indonesian: 'DOKTER', romaji: 'isha' },
      { japanese: 'にほん', kanji: '日本', indonesian: 'JEPANG', romaji: 'nihon' },
      { japanese: 'じん', kanji: '人', indonesian: 'ORANG (KEBANGSAAN)', romaji: 'jin' },
    ]
  },
  {
    id: 'ch2_study',
    name: 'CHAPTER 2: BELAJAR',
    icon: 'BookOpen',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'がっこう', kanji: '学校', indonesian: 'SEKOLAH', romaji: 'gakkou' },
      { japanese: 'せんせい', kanji: '先生', indonesian: 'GURU', romaji: 'sensei' },
      { japanese: 'がくせい', kanji: '学生', indonesian: 'SISWA', romaji: 'gakusei' },
      { japanese: 'ほん', kanji: '本', indonesian: 'BUKU', romaji: 'hon' },
      { japanese: 'べんきょう', kanji: '勉強', indonesian: 'BELAJAR', romaji: 'benkyou' },
      { japanese: 'きょうしつ', kanji: '教室', indonesian: 'RUANG KELAS', romaji: 'kyoushitsu' },
      { japanese: 'つくえ', kanji: '机', indonesian: 'MEJA', romaji: 'tsukue' },
      { japanese: 'いす', kanji: '椅子', indonesian: 'KURSI', romaji: 'isu' },
      { japanese: 'こくばん', kanji: '黒板', indonesian: 'PAPAN TULIS', romaji: 'kokuban' },
      { japanese: 'えんぴつ', kanji: '鉛筆', indonesian: 'PENSIL', romaji: 'enpitsu' },
      { japanese: 'かばん', kanji: '鞄', indonesian: 'TAS', romaji: 'kaban' },
      { japanese: 'とけい', kanji: '時計', indonesian: 'JAM', romaji: 'tokei' },
      { japanese: 'じしょ', kanji: '辞書', indonesian: 'KAMUS', romaji: 'jisho' },
      { japanese: 'のーと', indonesian: 'BUKU CATATAN', romaji: 'nooto' },
      { japanese: 'けしごむ', kanji: '消しゴム', indonesian: 'PENGHAPUS', romaji: 'keshigomu' },
    ]
  },
  {
    id: 'ch3_work',
    name: 'CHAPTER 3: PEKERJAAN',
    icon: 'Briefcase',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'しごと', kanji: '仕事', indonesian: 'PEKERJAAN', romaji: 'shigoto' },
      { japanese: 'かいしゃ', kanji: '会社', indonesian: 'PERUSAHAAN', romaji: 'kaisha' },
      { japanese: 'はたらく', kanji: '働く', indonesian: 'BEKERJA', romaji: 'hataraku' },
      { japanese: 'じかん', kanji: '時間', indonesian: 'WAKTU', romaji: 'jikan' },
      { japanese: 'これ', indonesian: 'INI', romaji: 'kore' },
      { japanese: 'それ', indonesian: 'ITU', romaji: 'sore' },
      { japanese: 'あれ', indonesian: 'ITU (JAUH)', romaji: 'are' },
      { japanese: 'どれ', indonesian: 'YANG MANA', romaji: 'dore' },
      { japanese: 'この', indonesian: 'INI (KATA SIFAT)', romaji: 'kono' },
      { japanese: 'その', indonesian: 'ITU (KATA SIFAT)', romaji: 'sono' },
      { japanese: 'あの', indonesian: 'ITU JAUH (KATA SIFAT)', romaji: 'ano' },
      { japanese: 'どの', indonesian: 'YANG MANA (KATA SIFAT)', romaji: 'dono' },
      { japanese: 'いそがしい', kanji: '忙しい', indonesian: 'SIBUK', romaji: 'isogashii' },
      { japanese: 'ひま', kanji: '暇', indonesian: 'SENGGANG', romaji: 'hima' },
      { japanese: 'やすみ', kanji: '休み', indonesian: 'LIBUR / ISTIRAHAT', romaji: 'yasumi' },
    ]
  },
  {
    id: 'ch4_friends',
    name: 'CHAPTER 4: TEMAN',
    icon: 'Users',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'ともだち', kanji: '友達', indonesian: 'TEMAN', romaji: 'tomodachi' },
      { japanese: 'ひと', kanji: '人', indonesian: 'ORANG', romaji: 'hito' },
      { japanese: 'あそぶ', kanji: '遊ぶ', indonesian: 'BERMAIN', romaji: 'asobu' },
      { japanese: 'まち', kanji: '町', indonesian: 'KOTA', romaji: 'machi' },
      { japanese: 'きる', kanji: '着る', indonesian: 'MEMAKAI (BAJU)', romaji: 'kiru' },
      { japanese: 'はく', kanji: '履く', indonesian: 'MEMAKAI (SEPATU/CELANA)', romaji: 'haku' },
      { japanese: 'かぶる', kanji: '被る', indonesian: 'MEMAKAI (TOPI)', romaji: 'kaburu' },
      { japanese: 'かける', kanji: '掛ける', indonesian: 'MEMAKAI (KACAMATA)', romaji: 'kakeru' },
      { japanese: 'しる', kanji: '知る', indonesian: 'TAHU / MENGENAL', romaji: 'shiru' },
      { japanese: 'はなす', kanji: '話す', indonesian: 'BERBICARA', romaji: 'hanasu' },
      { japanese: 'あう', kanji: '会う', indonesian: 'BERTEMU', romaji: 'au' },
      { japanese: 'いく', kanji: '行く', indonesian: 'PERGI', romaji: 'iku' },
      { japanese: 'くる', kanji: '来る', indonesian: 'DATANG', romaji: 'kuru' },
      { japanese: 'かえる', kanji: '帰る', indonesian: 'PULANG', romaji: 'kaeru' },
      { japanese: 'おとこ', kanji: '男', indonesian: 'LAKI-LAKI', romaji: 'otoko' },
    ]
  },
  {
    id: 'ch5_meals',
    name: 'CHAPTER 5: MAKANAN',
    icon: 'Utensils',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'ごはん', kanji: 'ご飯', indonesian: 'NASI / MAKANAN', romaji: 'gohan' },
      { japanese: 'あさごはん', kanji: '朝ご飯', indonesian: 'SARAPAN', romaji: 'asagohan' },
      { japanese: 'たべる', kanji: '食べる', indonesian: 'MAKAN', romaji: 'taberu' },
      { japanese: 'のむ', kanji: '飲む', indonesian: 'MINUM', romaji: 'nomu' },
      { japanese: 'みず', kanji: '水', indonesian: 'AIR', romaji: 'mizu' },
      { japanese: 'おちゃ', kanji: 'お茶', indonesian: 'TEH', romaji: 'ocha' },
      { japanese: 'こーひー', indonesian: 'KOPI', romaji: 'koohii' },
      { japanese: 'ぎゅうにゅう', kanji: '牛乳', indonesian: 'SUSU SAPI', romaji: 'gyuunyuu' },
      { japanese: 'ぱん', indonesian: 'ROTI', romaji: 'pan' },
      { japanese: 'たまご', kanji: '卵', indonesian: 'TELUR', romaji: 'tamago' },
      { japanese: 'にく', kanji: '肉', indonesian: 'DAGING', romaji: 'niku' },
      { japanese: 'さかな', kanji: '魚', indonesian: 'IKAN', romaji: 'sakana' },
      { japanese: 'やさい', kanji: '野菜', indonesian: 'SAYURAN', romaji: 'yasai' },
      { japanese: 'くだもの', kanji: '果物', indonesian: 'BUAH', romaji: 'kudamono' },
      { japanese: 'りょうり', kanji: '料理', indonesian: 'MASAKAN', romaji: 'ryouri' },
    ]
  },
  {
    id: 'ch6_hobbies',
    name: 'CHAPTER 6: HOBI',
    icon: 'Music',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'しゅみ', kanji: '趣味', indonesian: 'HOBI', romaji: 'shumi' },
      { japanese: 'おんがく', kanji: '音楽', indonesian: 'MUSIK', romaji: 'ongaku' },
      { japanese: 'てんき', kanji: '天気', indonesian: 'CUACA', romaji: 'tenki' },
      { japanese: 'はる', kanji: '春', indonesian: 'MUSIM SEMI', romaji: 'haru' },
      { japanese: 'なつ', kanji: '夏', indonesian: 'MUSIM PANAS', romaji: 'natsu' },
      { japanese: 'あき', kanji: '秋', indonesian: 'MUSIM GUGUR', romaji: 'aki' },
      { japanese: 'ふゆ', kanji: '冬', indonesian: 'MUSIM DINGIN', romaji: 'fuyu' },
      { japanese: 'はれ', kanji: '晴れ', indonesian: 'CERAH', romaji: 'hare' },
      { japanese: 'あめ', kanji: '雨', indonesian: 'HUJAN', romaji: 'ame' },
      { japanese: 'ゆき', kanji: '雪', indonesian: 'SALJU', romaji: 'yuki' },
      { japanese: 'かぜ', kanji: '風', indonesian: 'ANGIN', romaji: 'kaze' },
      { japanese: 'すぽーつ', indonesian: 'OLAHRAGA', romaji: 'supootsu' },
      { japanese: 'えいが', kanji: '映画', indonesian: 'FILM', romaji: 'eiga' },
      { japanese: 'しゃしん', kanji: '写真', indonesian: 'FOTO', romaji: 'shashin' },
      { japanese: 'うた', kanji: '歌', indonesian: 'LAGU', romaji: 'uta' },
    ]
  },
  {
    id: 'ch7_shopping',
    name: 'CHAPTER 7: BELANJA',
    icon: 'ShoppingCart',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'かいもの', kanji: '買い物', indonesian: 'BELANJA', romaji: 'kaimono' },
      { japanese: 'みせ', kanji: '店', indonesian: 'TOKO', romaji: 'mise' },
      { japanese: 'おかね', kanji: 'お金', indonesian: 'UANG', romaji: 'okane' },
      { japanese: 'かう', kanji: '買う', indonesian: 'MEMBELI', romaji: 'kau' },
      { japanese: 'たかい', kanji: '高い', indonesian: 'MAHAL / TINGGI', romaji: 'takai' },
      { japanese: 'やすい', kanji: '安い', indonesian: 'MURAH', romaji: 'yasui' },
      { japanese: 'あたらしい', kanji: '新しい', indonesian: 'BARU', romaji: 'atarashii' },
      { japanese: 'ふるい', kanji: '古い', indonesian: 'LAMA / KUNO', romaji: 'furui' },
      { japanese: 'おおきい', kanji: '大きい', indonesian: 'BESAR', romaji: 'ookii' },
      { japanese: 'ちいさい', kanji: '小さい', indonesian: 'KECIL', romaji: 'chiisai' },
      { japanese: 'かばん', kanji: '鞄', indonesian: 'TAS', romaji: 'kaban' },
      { japanese: 'くつ', kanji: '靴', indonesian: 'SEPATU', romaji: 'kutsu' },
      { japanese: 'ふく', kanji: '服', indonesian: 'PAKAIAN', romaji: 'fuku' },
      { japanese: 'とけい', kanji: '時計', indonesian: 'JAM', romaji: 'tokei' },
      { japanese: 'かめら', indonesian: 'KAMERA', romaji: 'kamera' },
    ]
  },
  {
    id: 'ch8_transport',
    name: 'CHAPTER 8: KENDARAAN',
    icon: 'Train',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'のりもの', kanji: '乗り物', indonesian: 'KENDARAAN', romaji: 'norimono' },
      { japanese: 'くるま', kanji: '車', indonesian: 'MOBIL', romaji: 'kuruma' },
      { japanese: 'でんしゃ', kanji: '電車', indonesian: 'KERETA', romaji: 'densha' },
      { japanese: 'えき', kanji: '駅', indonesian: 'STASIUN', romaji: 'eki' },
      { japanese: 'いく', kanji: '行く', indonesian: 'PERGI', romaji: 'iku' },
      { japanese: 'じてんしゃ', kanji: '自転車', indonesian: 'SEPEDA', romaji: 'jitensha' },
      { japanese: 'ばす', indonesian: 'BUS', romaji: 'basu' },
      { japanese: 'たくしー', indonesian: 'TAKSI', romaji: 'takushii' },
      { japanese: 'ひこうき', kanji: '飛行機', indonesian: 'PESAWAT', romaji: 'hikouki' },
      { japanese: 'ふね', kanji: '船', indonesian: 'KAPAL', romaji: 'fune' },
      { japanese: 'ちかてつ', kanji: '地下鉄', indonesian: 'KERETA BAWAH TANAH', romaji: 'chikatetsu' },
      { japanese: 'しんかんせん', kanji: '新幹線', indonesian: 'KERETA CEPAT', romaji: 'shinkansen' },
      { japanese: 'のる', kanji: '乗る', indonesian: 'NAIK (KENDARAAN)', romaji: 'noru' },
      { japanese: 'おりる', kanji: '降りる', indonesian: 'TURUN (KENDARAAN)', romaji: 'oriru' },
      { japanese: 'のりかえる', kanji: '乗り換える', indonesian: 'TRANSIT / PINDAH KENDARAAN', romaji: 'norikaeru' },
    ]
  },
  {
    id: 'ch9_living',
    name: 'CHAPTER 9: TEMPAT TINGGAL',
    icon: 'Home',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'いえ', kanji: '家', indonesian: 'RUMAH', romaji: 'ie' },
      { japanese: 'へや', kanji: '部屋', indonesian: 'KAMAR / RUANGAN', romaji: 'heya' },
      { japanese: 'でんき', kanji: '電気', indonesian: 'LISTRIK / LAMPU', romaji: 'denki' },
      { japanese: 'すむ', kanji: '住む', indonesian: 'TINGGAL', romaji: 'sumu' },
      { japanese: 'あたらしい', kanji: '新しい', indonesian: 'BARU', romaji: 'atarashii' },
      { japanese: 'あぱーと', indonesian: 'APARTEMEN', romaji: 'apaato' },
      { japanese: 'どあ', indonesian: 'PINTU', romaji: 'doa' },
      { japanese: 'まど', kanji: '窓', indonesian: 'JENDELA', romaji: 'mado' },
      { japanese: 'べっど', indonesian: 'TEMPAT TIDUR', romaji: 'beddo' },
      { japanese: 'ふとん', kanji: '布団', indonesian: 'FUTON', romaji: 'futon' },
      { japanese: 'といれ', indonesian: 'TOILET', romaji: 'toire' },
      { japanese: 'おふろ', kanji: 'お風呂', indonesian: 'BAK MANDI', romaji: 'ofuro' },
      { japanese: 'だいどころ', kanji: '台所', indonesian: 'DAPUR', romaji: 'daidokoro' },
      { japanese: 'れいぞうこ', kanji: '冷蔵庫', indonesian: 'KULKAS', romaji: 'reizouko' },
      { japanese: 'せんたくき', kanji: '洗濯機', indonesian: 'MESIN CUCI', romaji: 'sentakuki' },
    ]
  },
  {
    id: 'ch10_health',
    name: 'CHAPTER 10: KESEHATAN',
    icon: 'HeartPulse',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    words: [
      { japanese: 'びょうき', kanji: '病気', indonesian: 'PENYAKIT', romaji: 'byouki' },
      { japanese: 'げんき', kanji: '元気', indonesian: 'SEHAT / BERSEMANGAT', romaji: 'genki' },
      { japanese: 'からだ', kanji: '体', indonesian: 'TUBUH', romaji: 'karada' },
      { japanese: 'くすり', kanji: '薬', indonesian: 'OBAT', romaji: 'kusuri' },
      { japanese: 'いしゃ', kanji: '医者', indonesian: 'DOKTER', romaji: 'isha' },
      { japanese: 'びょういん', kanji: '病院', indonesian: 'RUMAH SAKIT', romaji: 'byouin' },
      { japanese: 'いたい', kanji: '痛い', indonesian: 'SAKIT (RASA)', romaji: 'itai' },
      { japanese: 'あたま', kanji: '頭', indonesian: 'KEPALA', romaji: 'atama' },
      { japanese: 'おなか', kanji: 'お腹', indonesian: 'PERUT', romaji: 'onaka' },
      { japanese: 'は', kanji: '歯', indonesian: 'GIGI', romaji: 'ha' },
      { japanese: 'め', kanji: '目', indonesian: 'MATA', romaji: 'me' },
      { japanese: 'みみ', kanji: '耳', indonesian: 'TELINGA', romaji: 'mimi' },
      { japanese: 'くち', kanji: '口', indonesian: 'MULUT', romaji: 'kuchi' },
      { japanese: 'て', kanji: '手', indonesian: 'TANGAN', romaji: 'te' },
      { japanese: 'あし', kanji: '足', indonesian: 'KAKI', romaji: 'ashi' },
    ]
  }
];

export const INITIAL_INVENTORY: Item[] = [
  {
    id: 'w1',
    name: 'KATANA RUSAK DAN HANCUR',
    type: 'WEAPON',
    description: 'Pedang tua yang sudah berkarat.',
    rarity: 'COMMON',
  },
  {
    id: 's1',
    name: 'PERISAI KAYU TIDAK BERDURI',
    type: 'SHIELD',
    description: 'Perisai kayu sederhana.',
    rarity: 'COMMON',
  },
  {
    id: 'a1',
    name: 'GELANG TEMBAGA BATU BIASA',
    type: 'ACCESSORY',
    description: 'Gelang tembaga kusam.',
    rarity: 'COMMON',
  },
  {
    id: 'c1',
    name: 'KAPSUL PENINGKAT ADRENALIN',
    type: 'CONSUMABLE',
    description: 'Memulihkan 50 HP',
    rarity: 'COMMON',
    count: 3
  }
];
