import { Level, Item, ItemTier } from './types';

export const MAX_INVENTORY_SLOTS = 99;

export const TIER_COLORS: Record<ItemTier, { text: string; border: string; bg: string }> = {
  1: { text: 'text-text-secondary', border: 'border-text-secondary', bg: 'bg-text-secondary/10' },
  2: { text: 'text-gray-400', border: 'border-gray-400', bg: 'bg-gray-400/10' },
  3: { text: 'text-yellow-500', border: 'border-yellow-500', bg: 'bg-yellow-500/10' },
  4: { text: 'text-purple-400', border: 'border-purple-400', bg: 'bg-purple-400/10' },
  5: { text: 'text-accent', border: 'border-accent', bg: 'bg-accent/10' },
};

export const INITIAL_LEVELS: Level[] = [
  {
    id: 'lvl_intro',
    name: 'Sapaan & Perkenalan',
    icon: 'UserCircle',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'わたし', kanji: '私', indonesian: 'SAYA', kanjiInfoOnly: true, romaji: 'watashi' },
      { japanese: 'あなた', indonesian: 'ANDA', romaji: 'anata' },
      { japanese: 'かぞく', kanji: '家族', indonesian: 'KELUARGA', kanjiInfoOnly: true, romaji: 'kazoku' },
      { japanese: 'おはよう', indonesian: 'SELAMAT PAGI', romaji: 'ohayou' },
      { japanese: 'なまえ', kanji: '名前', indonesian: 'NAMA', kanjiInfoOnly: true, romaji: 'namae' },
      { japanese: 'だれ', kanji: '誰', indonesian: 'SIAPA', kanjiInfoOnly: true, romaji: 'dare' },
      { japanese: 'なに', kanji: '何', indonesian: 'APA', romaji: 'nani' },
      { japanese: 'はい', indonesian: 'IYA', romaji: 'hai' },
      { japanese: 'いいえ', indonesian: 'TIDAK', romaji: 'iie' },
      { japanese: 'せんせい', kanji: '先生', indonesian: 'GURU', romaji: 'sensei' },
      { japanese: 'がくせい', kanji: '学生', indonesian: 'SISWA', romaji: 'gakusei' },
      { japanese: 'いしゃ', kanji: '医者', indonesian: 'DOKTER', kanjiInfoOnly: true, romaji: 'isha' },
      { japanese: 'にほん', kanji: '日本', indonesian: 'JEPANG', romaji: 'nihon' },
      { japanese: 'じん', kanji: '人', indonesian: 'ORANG (NEGARA)', romaji: 'jin' },
      { japanese: 'こんにちは', indonesian: 'HALO / SIANG', romaji: 'konnichiwa' },
      { japanese: 'こんばんは', indonesian: 'SELAMAT MALAM', romaji: 'konbanwa' },
      { japanese: 'おやすみ', kanji: 'お休み', indonesian: 'SELAMAT TIDUR', romaji: 'oyasumi' },
      { japanese: 'ありがとう', indonesian: 'TERIMA KASIH', romaji: 'arigatou' },
      { japanese: 'ともだち', kanji: '友達', indonesian: 'TEMAN', kanjiInfoOnly: true, romaji: 'tomodachi' },
      { japanese: 'こども', kanji: '子供', indonesian: 'ANAK-ANAK', kanjiInfoOnly: true, romaji: 'kodomo' },
    ]
  },
  {
    id: 'lvl_school',
    name: 'Sekolah & Belajar',
    icon: 'BookOpen',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'がっこう', kanji: '学校', indonesian: 'SEKOLAH', romaji: 'gakkou' },
      { japanese: 'べんきょう', kanji: '勉強', indonesian: 'BELAJAR', romaji: 'benkyou' },
      { japanese: 'きょうしつ', kanji: '教室', indonesian: 'RUANG KELAS', kanjiInfoOnly: true, romaji: 'kyoushitsu' },
      { japanese: 'つくえ', kanji: '机', indonesian: 'MEJA', kanjiInfoOnly: true, romaji: 'tsukue' },
      { japanese: 'いす', kanji: '椅子', indonesian: 'KURSI', kanjiInfoOnly: true, romaji: 'isu' },
      { japanese: 'ほん', kanji: '本', indonesian: 'BUKU', kanjiInfoOnly: true, romaji: 'hon' },
      { japanese: 'じしょ', kanji: '辞書', indonesian: 'KAMUS', kanjiInfoOnly: true, romaji: 'jisho' },
      { japanese: 'のーと', indonesian: 'CATATAN', romaji: 'nooto' },
      { japanese: 'えんぴつ', kanji: '鉛筆', indonesian: 'PENSIL', kanjiInfoOnly: true, romaji: 'enpitsu' },
      { japanese: 'びじゅつ', kanji: '美術', indonesian: 'SENI', romaji: 'bijutsu' },
      { japanese: 'きょう', kanji: '今日', indonesian: 'HARI INI', romaji: 'kyou' },
      { japanese: 'きのう', kanji: '昨日', indonesian: 'KEMARIN', kanjiInfoOnly: true, romaji: 'kinou' },
      { japanese: 'あした', kanji: '明日', indonesian: 'BESOK', kanjiInfoOnly: true, romaji: 'ashita' },
      { japanese: 'よむ', kanji: '読む', indonesian: 'MEMBACA', romaji: 'yomu' },
      { japanese: 'かく', kanji: '書く', indonesian: 'MENULIS', romaji: 'kaku' },
      { japanese: 'きく', kanji: '聞く', indonesian: 'MENDENGAR', romaji: 'kiku' },
      { japanese: 'わかる', kanji: '分かる', indonesian: 'MENGERTI', romaji: 'wakaru' },
    ]
  },
  {
    id: 'lvl_action_verbs',
    name: 'Aktivitas Harian',
    icon: 'Zap',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'たべる', kanji: '食べる', indonesian: 'MAKAN', romaji: 'taberu' },
      { japanese: 'のむ', kanji: '飲む', indonesian: 'MINUM', romaji: 'nomu' },
      { japanese: 'いく', kanji: '行く', indonesian: 'PERGI', romaji: 'iku' },
      { japanese: 'くる', kanji: '来る', indonesian: 'DATANG', romaji: 'kuru' },
      { japanese: 'かえる', kanji: '帰る', indonesian: 'PULANG', kanjiInfoOnly: true, romaji: 'kaeru' },
      { japanese: 'ねる', kanji: '寝る', indonesian: 'TIDUR', romaji: 'neru' },
      { japanese: 'おきる', kanji: '起きる', indonesian: 'BANGUN', romaji: 'okiru' },
      { japanese: 'みる', kanji: '見る', indonesian: 'MELIHAT', romaji: 'miru' },
      { japanese: 'はなす', kanji: '話す', indonesian: 'BERBICARA', romaji: 'hanasu' },
      { japanese: 'あう', kanji: '会う', indonesian: 'BERTEMU', romaji: 'au' },
      { japanese: 'まつ', kanji: '待つ', indonesian: 'MENUNGGU', romaji: 'matsu' },
      { japanese: 'かう', kanji: '買う', indonesian: 'MEMBELI', romaji: 'kau' },
      { japanese: 'とる', kanji: '撮る', indonesian: 'MENGAMBIL (FOTO)', kanjiInfoOnly: true, romaji: 'toru' },
      { japanese: 'つく', kanji: '着く', indonesian: 'SAMPAI', kanjiInfoOnly: true, romaji: 'tsuku' },
      { japanese: 'でる', kanji: '出る', indonesian: 'KELUAR', romaji: 'deru' },
      { japanese: 'はいる', kanji: '入る', indonesian: 'MASUK', romaji: 'hairu' },
    ]
  },
  {
    id: 'lvl_food',
    name: 'Makanan & Minuman',
    icon: 'Utensils',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'ごはん', kanji: 'ご飯', indonesian: 'NASI', kanjiInfoOnly: true, romaji: 'gohan' },
      { japanese: 'みず', kanji: '水', indonesian: 'AIR', romaji: 'mizu' },
      { japanese: 'おちゃ', kanji: 'お茶', indonesian: 'TEH', kanjiInfoOnly: true, romaji: 'ocha' },
      { japanese: 'こーひー', indonesian: 'KOPI', romaji: 'koohii' },
      { japanese: 'にく', kanji: '肉', indonesian: 'DAGING', romaji: 'niku' },
      { japanese: 'さかな', kanji: '魚', indonesian: 'IKAN', kanjiInfoOnly: true, romaji: 'sakana' },
      { japanese: 'やさい', kanji: '野菜', indonesian: 'SAYURAN', kanjiInfoOnly: true, romaji: 'yasai' },
      { japanese: 'くだもの', kanji: '果物', indonesian: 'BUAH', kanjiInfoOnly: true, romaji: 'kudamono' },
      { japanese: 'たまご', kanji: '卵', indonesian: 'TELUR', kanjiInfoOnly: true, romaji: 'tamago' },
      { japanese: 'ぱん', indonesian: 'ROTI', romaji: 'pan' },
      { japanese: 'ぎゅうにゅう', kanji: '牛乳', indonesian: 'SUSU', kanjiInfoOnly: true, romaji: 'gyuunyuu' },
      { japanese: 'あまい', kanji: '甘い', indonesian: 'MANIS', kanjiInfoOnly: true, romaji: 'amai' },
      { japanese: 'からい', kanji: '辛い', indonesian: 'PEDAS', kanjiInfoOnly: true, romaji: 'karai' },
      { japanese: 'おいしい', indonesian: 'ENAK', romaji: 'oishii' },
      { japanese: 'おなか', kanji: 'お腹', indonesian: 'PERUT', kanjiInfoOnly: true, romaji: 'onaka' },
    ]
  },
  {
    id: 'lvl_home',
    name: 'Rumah & Kamar',
    icon: 'Home',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'いえ', kanji: '家', indonesian: 'RUMAH', kanjiInfoOnly: true, romaji: 'ie' },
      { japanese: 'へや', kanji: '部屋', indonesian: 'KAMAR', kanjiInfoOnly: true, romaji: 'heya' },
      { japanese: 'どあ', indonesian: 'PINTU', romaji: 'doa' },
      { japanese: 'まど', kanji: '窓', indonesian: 'JENDELA', kanjiInfoOnly: true, romaji: 'mado' },
      { japanese: 'べっど', indonesian: 'TEMPAT TIDUR', romaji: 'beddo' },
      { japanese: 'といれ', indonesian: 'TOILET', romaji: 'toire' },
      { japanese: 'だいどころ', kanji: '台所', indonesian: 'DAPUR', kanjiInfoOnly: true, romaji: 'daidokoro' },
      { japanese: 'てれび', indonesian: 'TELEVISI', romaji: 'terebi' },
      { japanese: 'れいぞうこ', kanji: '冷蔵庫', indonesian: 'KULKAS', kanjiInfoOnly: true, romaji: 'reizouko' },
      { japanese: 'せんたく', kanji: '洗濯', indonesian: 'CUCI BAJU', kanjiInfoOnly: true, romaji: 'sentaku' },
      { japanese: 'そうじ', kanji: '掃除', indonesian: 'BERSIH-BERSIH', romaji: 'souji' },
      { japanese: 'にわ', kanji: '庭', indonesian: 'HALAMAN', kanjiInfoOnly: true, romaji: 'niwa' },
      { japanese: 'かいだん', kanji: '階段', indonesian: 'TANGGA', kanjiInfoOnly: true, romaji: 'kaidan' },
    ]
  },
  {
    id: 'lvl_weather',
    name: 'Cuaca & Alam',
    icon: 'Cloud',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'てんき', kanji: '天気', indonesian: 'CUACA', romaji: 'tenki' },
      { japanese: 'はれ', kanji: '晴れ', indonesian: 'CERAH', romaji: 'hare' },
      { japanese: 'あめ', kanji: '雨', indonesian: 'HUJAN', romaji: 'ame' },
      { japanese: 'ゆき', kanji: '雪', indonesian: 'SALJU', romaji: 'yuki' },
      { japanese: 'かぜ', kanji: '風', indonesian: 'ANGIN', kanjiInfoOnly: true, romaji: 'kaze' },
      { japanese: 'くも', kanji: '雲', indonesian: 'AWAN', romaji: 'kumo' },
      { japanese: 'そら', kanji: '空', indonesian: 'LANGIT', romaji: 'sora' },
      { japanese: 'うみ', kanji: '海', indonesian: 'LAUT', kanjiInfoOnly: true, romaji: 'umi' },
      { japanese: 'やま', kanji: '山', indonesian: 'GUNUNG', romaji: 'yama' },
      { japanese: 'かわ', kanji: '川', indonesian: 'SUNGAI', romaji: 'kawa' },
      { japanese: 'き', kanji: '木', indonesian: 'POHON', romaji: 'ki' },
      { japanese: 'はな', kanji: '花', indonesian: 'BUNGA', romaji: 'hana' },
      { japanese: 'たいよう', kanji: '太陽', indonesian: 'MATAHARI', romaji: 'taiyou' },
    ]
  },
  {
    id: 'lvl_time',
    name: 'Waktu & Tanggal',
    icon: 'Clock',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'じかん', kanji: '時間', indonesian: 'WAKTU', romaji: 'jikan' },
      { japanese: 'いま', kanji: '今', indonesian: 'SEKARANG', romaji: 'ima' },
      { japanese: 'あさ', kanji: '朝', indonesian: 'PAGI', romaji: 'asa' },
      { japanese: 'ひる', kanji: '昼', indonesian: 'SIANG', romaji: 'hiru' },
      { japanese: 'ばん', kanji: '晩', indonesian: 'MALAM', kanjiInfoOnly: true, romaji: 'ban' },
      { japanese: 'よる', kanji: '夜', indonesian: 'MALAM (LATE)', romaji: 'yoru' },
      { japanese: 'しゅう', kanji: '週', indonesian: 'MINGGU', romaji: 'shuu' },
      { japanese: 'つき', kanji: '月', indonesian: 'BULAN', romaji: 'tsuki' },
      { japanese: 'とし', kanji: '年', indonesian: 'TAHUN', romaji: 'toshi' },
      { japanese: 'せんしゅう', kanji: '先週', indonesian: 'MINGGU LALU', romaji: 'senshuu' },
      { japanese: 'らいしゅう', kanji: '来週', indonesian: 'MINGGU DEPAN', romaji: 'raishuu' },
      { japanese: 'あさって', kanji: '明後日', indonesian: 'LUSA', romaji: 'asatte' },
      { japanese: 'まいにち', kanji: '毎日', indonesian: 'SETIAP HARI', romaji: 'mainichi' },
    ]
  },
  {
    id: 'lvl_body',
    name: 'Tubuh & Kesehatan',
    icon: 'HeartPulse',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'からだ', kanji: '体', indonesian: 'TUBUH', kanjiInfoOnly: true, romaji: 'karada' },
      { japanese: 'あたま', kanji: '頭', indonesian: 'KEPALA', kanjiInfoOnly: true, romaji: 'atama' },
      { japanese: 'め', kanji: '目', indonesian: 'MATA', romaji: 'me' },
      { japanese: 'みみ', kanji: '耳', indonesian: 'TELINGA', romaji: 'mimi' },
      { japanese: 'はな', kanji: '鼻', indonesian: 'HIDUNG', romaji: 'hana' },
      { japanese: 'くち', kanji: '口', indonesian: 'MULUT', romaji: 'kuchi' },
      { japanese: 'て', kanji: '手', indonesian: 'TANGAN', romaji: 'te' },
      { japanese: 'あし', kanji: '足', indonesian: 'KAKI', romaji: 'ashi' },
      { japanese: 'は', kanji: '歯', indonesian: 'GIGI', kanjiInfoOnly: true, romaji: 'ha' },
      { japanese: 'びょうき', kanji: '病気', indonesian: 'SAKIT', kanjiInfoOnly: true, romaji: 'byouki' },
      { japanese: 'くすり', kanji: '薬', indonesian: 'OBAT', kanjiInfoOnly: true, romaji: 'kusuri' },
      { japanese: 'びょういん', kanji: '病院', indonesian: 'RUMAH SAKIT', kanjiInfoOnly: true, romaji: 'byouin' },
    ]
  },
  {
    id: 'lvl_clothing',
    name: 'Pakaian & Mode',
    icon: 'Shirt',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'ふく', kanji: '服', indonesian: 'PAKAIAN', kanjiInfoOnly: true, romaji: 'fuku' },
      { japanese: 'しゃつ', indonesian: 'KEMEJA', romaji: 'shatsu' },
      { japanese: 'ずぼん', indonesian: 'CELANA', romaji: 'zubon' },
      { japanese: 'くつ', kanji: '靴', indonesian: 'SEPATU', kanjiInfoOnly: true, romaji: 'kutsu' },
      { japanese: 'くつした', kanji: '靴下', indonesian: 'KAOS KAKI', kanjiInfoOnly: true, romaji: 'kutsushita' },
      { japanese: 'ぼうし', kanji: '帽子', indonesian: 'TOPI', kanjiInfoOnly: true, romaji: 'boushi' },
      { japanese: 'めがね', kanji: '眼鏡', indonesian: 'KACAMATA', kanjiInfoOnly: true, romaji: 'megane' },
      { japanese: 'かばん', kanji: '鞄', indonesian: 'TAS', kanjiInfoOnly: true, romaji: 'kaban' },
      { japanese: 'きる', kanji: '着る', indonesian: 'MEMAKAI (ATASAN)', kanjiInfoOnly: true, romaji: 'kiru' },
      { japanese: 'はく', kanji: '履く', indonesian: 'MEMAKAI (BAWAHAN)', kanjiInfoOnly: true, romaji: 'haku' },
    ]
  },
  {
    id: 'lvl_animals',
    name: 'Hewan & Binatang',
    icon: 'Dog',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'どうぶつ', kanji: '動物', indonesian: 'HEWAN', kanjiInfoOnly: true, romaji: 'doubutsu' },
      { japanese: 'いぬ', kanji: '犬', indonesian: 'ANJING', romaji: 'inu' },
      { japanese: 'ねこ', kanji: '猫', indonesian: 'KUCING', romaji: 'neko' },
      { japanese: 'とり', kanji: '鳥', indonesian: 'BURUNG', kanjiInfoOnly: true, romaji: 'tori' },
      { japanese: 'へび', kanji: '蛇', indonesian: 'ULAR', romaji: 'hebi' },
      { japanese: 'うま', kanji: '馬', indonesian: 'KUDA', romaji: 'uma' },
      { japanese: 'うし', kanji: '牛', indonesian: 'SAPI', romaji: 'ushi' },
      { japanese: 'ぶた', kanji: '豚', indonesian: 'BABI', romaji: 'buta' },
      { japanese: 'うさぎ', kanji: '兎', indonesian: 'KELINCI', romaji: 'usagi' },
      { japanese: 'さる', kanji: '猿', indonesian: 'MONYET', romaji: 'saru' },
      { japanese: 'むし', kanji: '虫', indonesian: 'SERANGGA', romaji: 'mushi' },
    ]
  },
  {
    id: 'lvl_transport',
    name: 'Transportasi',
    icon: 'Train',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'のりもの', kanji: '乗り物', indonesian: 'KENDARAAN', romaji: 'norimono' },
      { japanese: 'くるま', kanji: '車', indonesian: 'MOBIL', romaji: 'kuruma' },
      { japanese: 'でんしゃ', kanji: '電車', indonesian: 'KERETA', romaji: 'densha' },
      { japanese: 'ばす', indonesian: 'BUS', romaji: 'basu' },
      { japanese: 'ひこうき', kanji: '飛行機', indonesian: 'PESAWAT', kanjiInfoOnly: true, romaji: 'hikouki' },
      { japanese: 'ふね', kanji: '船', indonesian: 'KAPAL', romaji: 'fune' },
      { japanese: 'じてんしゃ', kanji: '自転車', indonesian: 'SEPEDA', kanjiInfoOnly: true, romaji: 'jitensha' },
      { japanese: 'えき', kanji: '駅', indonesian: 'STASIUN', kanjiInfoOnly: true, romaji: 'eki' },
      { japanese: 'みち', kanji: '道', indonesian: 'JALAN', kanjiInfoOnly: true, romaji: 'michi' },
    ]
  },
  {
    id: 'lvl_adjectives_i',
    name: 'Kata Sifat I',
    icon: 'Info',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'たかい', kanji: '高い', indonesian: 'MAHAL / TINGGI', kanjiInfoOnly: true, romaji: 'takai' },
      { japanese: 'やすい', kanji: '安い', indonesian: 'MURAH', romaji: 'yasui' },
      { japanese: 'あたらしい', kanji: '新しい', indonesian: 'BARU', kanjiInfoOnly: true, romaji: 'atarashii' },
      { japanese: 'ふるい', kanji: '古い', indonesian: 'LAMA', kanjiInfoOnly: true, romaji: 'furui' },
      { japanese: 'いい', indonesian: 'BAGUS', romaji: 'ii' },
      { japanese: 'わるい', kanji: '悪い', indonesian: 'BURUK', romaji: 'warui' },
      { japanese: 'あつい', kanji: '暑い', indonesian: 'PANAS (CUACA)', kanjiInfoOnly: true, romaji: 'atsui' },
      { japanese: 'さむい', kanji: '寒い', indonesian: 'DINGIN (CUACA)', kanjiInfoOnly: true, romaji: 'samui' },
      { japanese: 'おおきい', kanji: '大きい', indonesian: 'BESAR', kanjiInfoOnly: true, romaji: 'ookii' },
      { japanese: 'ちいさい', kanji: '小さい', indonesian: 'KECIL', kanjiInfoOnly: true, romaji: 'chiisai' },
      { japanese: 'むずかしい', kanji: '難しい', indonesian: 'SULIT', kanjiInfoOnly: true, romaji: 'muzukashii' },
      { japanese: 'やさしい', kanji: '易しい', indonesian: 'MUDAH', kanjiInfoOnly: true, romaji: 'yasashii' },
    ]
  },
  {
    id: 'lvl_adjectives_na',
    name: 'Kata Sifat NA',
    icon: 'Info',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'すき', kanji: '好き', indonesian: 'SUKA', kanjiInfoOnly: true, romaji: 'suki' },
      { japanese: 'きらい', kanji: '嫌い', indonesian: 'BENCI', kanjiInfoOnly: true, romaji: 'kirai' },
      { japanese: 'じょうず', kanji: '上手', indonesian: 'PANDAI', romaji: 'jouzu' },
      { japanese: 'へた', kanji: '下手', indonesian: 'BODOH / TIDAK PANDAI', romaji: 'heta' },
      { japanese: 'しずか', kanji: '静か', indonesian: 'TENANG', kanjiInfoOnly: true, romaji: 'shizuka' },
      { japanese: 'にぎやか', indonesian: 'RAMAI', romaji: 'nigiyaka' },
      { japanese: 'べんり', kanji: '便利', indonesian: 'PRAKTIS', kanjiInfoOnly: true, romaji: 'benri' },
      { japanese: 'げんき', kanji: '元気', indonesian: 'SEHAT', kanjiInfoOnly: true, romaji: 'genki' },
      { japanese: 'ひま', kanji: '暇', indonesian: 'SENGGANG', kanjiInfoOnly: true, romaji: 'hima' },
      { japanese: 'たいへん', kanji: '大変', indonesian: 'SULIT / BERAT', kanjiInfoOnly: true, romaji: 'taihen' },
    ]
  },
  {
    id: 'lvl_places',
    name: 'Tempat & Lokasi',
    icon: 'MapPin',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'ここ', indonesian: 'DI SINI', romaji: 'koko' },
      { japanese: 'そこ', indonesian: 'DI SITU', romaji: 'soko' },
      { japanese: 'あそこ', indonesian: 'DI SANA', romaji: 'asoko' },
      { japanese: 'どこ', indonesian: 'DI MANA', romaji: 'doko' },
      { japanese: 'みせ', kanji: '店', indonesian: 'TOKO', romaji: 'mise' },
      { japanese: 'ぎんこう', kanji: '銀行', indonesian: 'BANK', romaji: 'ginkou' },
      { japanese: 'ゆうびんきょく', kanji: '郵便局', indonesian: 'KANTOR POS', romaji: 'yuubinkyoku' },
      { japanese: 'としょかん', kanji: '図書館', indonesian: 'PERPUSTAKAAN', kanjiInfoOnly: true, romaji: 'toshokan' },
      { japanese: 'とうきょう', kanji: '東京', indonesian: 'TOKYO', romaji: 'toukyou' },
      { japanese: 'まち', kanji: '町', indonesian: 'KOTA', kanjiInfoOnly: true, romaji: 'machi' },
    ]
  },
  {
    id: 'lvl_verbs_action',
    name: 'Tindakan Fisik',
    icon: 'Zap',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'あるく', kanji: '歩く', indonesian: 'BERJALAN', kanjiInfoOnly: true, romaji: 'aruku' },
      { japanese: 'はしる', kanji: '走る', indonesian: 'BERLARI', kanjiInfoOnly: true, romaji: 'hashiru' },
      { japanese: 'とぶ', kanji: '飛ぶ', indonesian: 'TERBANG', kanjiInfoOnly: true, romaji: 'tobu' },
      { japanese: 'およぐ', kanji: '泳ぐ', indonesian: 'BERENANG', kanjiInfoOnly: true, romaji: 'oyogu' },
      { japanese: 'たつ', kanji: '立つ', indonesian: 'BERDIRI', kanjiInfoOnly: true, romaji: 'tatsu' },
      { japanese: 'すわる', kanji: '座る', indonesian: 'DUDUK', kanjiInfoOnly: true, romaji: 'suwaru' },
      { japanese: 'あそぶ', kanji: '遊ぶ', indonesian: 'BERMAIN', kanjiInfoOnly: true, romaji: 'asobu' },
      { japanese: 'いそぐ', kanji: '急ぐ', indonesian: 'TERBURU-BURU', romaji: 'isogu' },
      { japanese: 'やすむ', kanji: '休む', indonesian: 'BERISTIRAHAT', romaji: 'yasumu' },
      { japanese: 'はたらく', kanji: '働く', indonesian: 'BEKERJA', kanjiInfoOnly: true, romaji: 'hataraku' },
    ]
  },
  {
    id: 'lvl_objects',
    name: 'Benda Sekitar',
    icon: 'Package',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'でんき', kanji: '電気', indonesian: 'LISTRIK / LAMPU', romaji: 'denki' },
      { japanese: 'かめら', indonesian: 'KAMERA', romaji: 'kamera' },
      { japanese: 'ぱそこん', indonesian: 'KOMPUTER', romaji: 'pasokon' },
      { japanese: 'けいたい', kanji: '携帯', indonesian: 'PONSEL', romaji: 'keitai' },
      { japanese: 'てがみ', kanji: '手紙', indonesian: 'SURAT', kanjiInfoOnly: true, romaji: 'tegami' },
      { japanese: 'かぎ', kanji: '鍵', indonesian: 'KUNCI', kanjiInfoOnly: true, romaji: 'kagi' },
      { japanese: 'かさ', kanji: '傘', indonesian: 'PAYUNG', kanjiInfoOnly: true, romaji: 'kasa' },
      { japanese: 'はこ', kanji: '箱', indonesian: 'KOTAK', kanjiInfoOnly: true, romaji: 'hako' },
      { japanese: 'ごみ', indonesian: 'SAMPAH', romaji: 'gomi' },
    ]
  },
  {
    id: 'lvl_jobs',
    name: 'Pekerjaan',
    icon: 'Briefcase',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'しごと', kanji: '仕事', indonesian: 'PEKERJAAN', kanjiInfoOnly: true, romaji: 'shigoto' },
      { japanese: 'かいしゃいん', kanji: '会社員', indonesian: 'KARYAWAN', romaji: 'kaishain' },
      { japanese: 'ぎんこういん', kanji: '銀行員', indonesian: 'PEGAWAI BANK', romaji: 'ginkouin' },
      { japanese: 'きょうし', kanji: '教師', indonesian: 'PENGAJAR', romaji: 'kyoushi' },
      { japanese: 'はいしゃ', kanji: '歯医者', indonesian: 'DOKTER GIGI', romaji: 'haisha' },
      { japanese: 'べんごし', kanji: '弁護士', indonesian: 'PENGACARA', romaji: 'bengoshi' },
      { japanese: 'こうむいん', kanji: '公務員', indonesian: 'PEGAWAI NEGERI', romaji: 'koumuin' },
      { japanese: 'てんいん', kanji: '店員', indonesian: 'PELAYAN TOKO', romaji: 'tenin' },
    ]
  },
  {
    id: 'lvl_leisure',
    name: 'Hobi & Hiburan',
    icon: 'Music',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'おんがく', kanji: '音楽', indonesian: 'MUSIK', kanjiInfoOnly: true, romaji: 'ongaku' },
      { japanese: 'うた', kanji: '歌', indonesian: 'LAGU', kanjiInfoOnly: true, romaji: 'uta' },
      { japanese: 'えいが', kanji: '映画', indonesian: 'FILM', kanjiInfoOnly: true, romaji: 'eiga' },
      { japanese: 'しゃしん', kanji: '写真', indonesian: 'FOTO', kanjiInfoOnly: true, romaji: 'shashin' },
      { japanese: 'え', kanji: '絵', indonesian: 'LUKISAN', kanjiInfoOnly: true, romaji: 'e' },
      { japanese: 'どくしょ', kanji: '読書', indonesian: 'MEMBACA BUKU', romaji: 'dokusho' },
      { japanese: 'りょこう', kanji: '旅行', indonesian: 'WISATA', kanjiInfoOnly: true, romaji: 'ryokou' },
      { japanese: 'すぽーつ', indonesian: 'OLAHRAGA', romaji: 'supootsu' },
    ]
  },
  {
    id: 'lvl_shopping_adv',
    name: 'Belanja & Uang',
    icon: 'ShoppingCart',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'おかね', kanji: 'お金', indonesian: 'UANG', romaji: 'okane' },
      { japanese: 'げんきん', kanji: '現金', indonesian: 'TUNAI', romaji: 'genkin' },
      { japanese: 'かーど', indonesian: 'KARTU', romaji: 'kaado' },
      { japanese: 'うりば', kanji: '売り場', indonesian: 'TEMPAT JUALAN', romaji: 'uriba' },
      { japanese: 'ねだん', kanji: '値段', indonesian: 'HARGA', romaji: 'nedan' },
      { japanese: 'おつり', indonesian: 'KEMBALIAN', romaji: 'otsuri' },
      { japanese: 'さいふ', kanji: '財布', indonesian: 'DOMPET', romaji: 'saifu' },
    ]
  },
  {
    id: 'lvl_verbs_advanced',
    name: 'Kata Kerja Lanjutan',
    icon: 'Zap',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'おもいだす', kanji: '思い出す', indonesian: 'MENGINGAT', romaji: 'omoidasu' },
      { japanese: 'かんがえる', kanji: '考える', indonesian: 'BERPIKIR', romaji: 'kangaeru' },
      { japanese: 'しらべる', kanji: '調べる', indonesian: 'MEMERIKSA', romaji: 'shiraberu' },
      { japanese: 'つかう', kanji: '使う', indonesian: 'MENGGUNAKAN', kanjiInfoOnly: true, romaji: 'tsukau' },
      { japanese: 'つくる', kanji: '作る', indonesian: 'MEMBUAT', kanjiInfoOnly: true, romaji: 'tsukuru' },
      { japanese: 'なおす', kanji: '直す', indonesian: 'MEMPERBAIKI', romaji: 'naosu' },
      { japanese: 'ならう', kanji: '習う', indonesian: 'BELAJAR (DARI GURU)', kanjiInfoOnly: true, romaji: 'narau' },
      { japanese: 'おしえる', kanji: '教える', indonesian: 'MENGAJAR', romaji: 'oshieru' },
    ]
  },
  {
    id: 'lvl_colors',
    name: 'Warna & Bentuk',
    icon: 'Palette',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'いろ', kanji: '色', indonesian: 'WARNA', romaji: 'iro' },
      { japanese: 'あか', kanji: '赤', indonesian: 'MERAH', romaji: 'aka' },
      { japanese: 'あお', kanji: '青', indonesian: 'BIRU', romaji: 'ao' },
      { japanese: 'きいろ', kanji: '黄色', indonesian: 'KUNING', romaji: 'kiiro' },
      { japanese: 'しろ', kanji: '白', indonesian: 'PUTIH', romaji: 'shiro' },
      { japanese: 'くろ', kanji: '黒', indonesian: 'HITAM', romaji: 'kuro' },
      { japanese: 'みどり', kanji: '緑', indonesian: 'HIJAU', romaji: 'midori' },
      { japanese: 'まる', kanji: '丸', indonesian: 'LINGKARAN', romaji: 'maru' },
      { japanese: 'しかく', kanji: '四角', indonesian: 'PERSEGI', romaji: 'shikaku' },
    ]
  },
  {
    id: 'lvl_directions',
    name: 'Arah & Posisi',
    icon: 'Compass',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'うえ', kanji: '上', indonesian: 'ATAS', romaji: 'ue' },
      { japanese: 'した', kanji: '下', indonesian: 'BAWAH', romaji: 'shita' },
      { japanese: 'まえ', kanji: '前', indonesian: 'DEPAN', romaji: 'mae' },
      { japanese: 'うしろ', kanji: '後ろ', indonesian: 'BELAKANG', romaji: 'ushiro' },
      { japanese: 'なか', kanji: '中', indonesian: 'DALAM', romaji: 'naka' },
      { japanese: 'そと', kanji: '外', indonesian: 'LUAR', romaji: 'soto' },
      { japanese: 'ひだり', kanji: '左', indonesian: 'KIRI', romaji: 'hidari' },
      { japanese: 'みぎ', kanji: '右', indonesian: 'KANAN', romaji: 'migi' },
      { japanese: 'きた', kanji: '北', indonesian: 'UTARA', romaji: 'kita' },
      { japanese: 'みなみ', kanji: '南', indonesian: 'SELATAN', romaji: 'minami' },
      { japanese: 'ひがし', kanji: '東', indonesian: 'TIMUR', romaji: 'higashi' },
      { japanese: 'にし', kanji: '西', indonesian: 'BARAT', romaji: 'nishi' },
    ]
  },
  {
    id: 'lvl_city',
    name: 'Kehidupan Kota',
    icon: 'Building2',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'びる', indonesian: 'GEDUNG', romaji: 'biru' },
      { japanese: 'こうえん', kanji: '公園', indonesian: 'TAMAN', kanjiInfoOnly: true, romaji: 'kouen' },
      { japanese: 'どおり', kanji: '通り', indonesian: 'JALAN RAYA', romaji: 'doori' },
      { japanese: 'こうもん', kanji: '校門', indonesian: 'GERBANG SEKOLAH', romaji: 'koumon' },
      { japanese: 'えきまえ', kanji: '駅前', indonesian: 'DEPAN STASIUN', romaji: 'ekimae' },
      { japanese: 'きっさてん', kanji: '喫茶店', indonesian: 'KAFE', kanjiInfoOnly: true, romaji: 'kissaten' },
      { japanese: 'れすとらん', indonesian: 'RESTORAN', romaji: 'resutoran' },
    ]
  },
  {
    id: 'lvl_nature_adv',
    name: 'Alam Lanjutan',
    icon: 'Mountain',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'ほし', kanji: '星', indonesian: 'BINTANG', romaji: 'hoshi' },
      { japanese: 'つき', kanji: '月', indonesian: 'BULAN (SKY)', romaji: 'tsuki' },
      { japanese: 'もり', kanji: '森', indonesian: 'HUTAN', romaji: 'mori' },
      { japanese: 'いけ', kanji: '池', indonesian: 'KOLAM', kanjiInfoOnly: true, romaji: 'ike' },
      { japanese: 'いし', kanji: '石', indonesian: 'BATU', romaji: 'ishi' },
      { japanese: 'すな', kanji: '砂', indonesian: 'PASIR', romaji: 'suna' },
    ]
  },
  {
    id: 'lvl_abstract',
    name: 'Konsep Dasar',
    icon: 'Lightbulb',
    isCompleted: false,
    bestTime: 0,
    unlockedWordCount: 10,
    seenWordIndices: [],
    favoriteWordIndices: [],
    words: [
      { japanese: 'ことば', kanji: '言葉', indonesian: 'KATA / BAHASA', kanjiInfoOnly: true, romaji: 'kotoba' },
      { japanese: 'ゆめ', kanji: '夢', indonesian: 'MIMPI', romaji: 'yume' },
      { japanese: 'あい', kanji: '愛', indonesian: 'CINTA', romaji: 'ai' },
      { japanese: 'こころ', kanji: '心', indonesian: 'HATI / JIWA', romaji: 'kokoro' },
      { japanese: 'ちから', kanji: '力', indonesian: 'TENAGA / KEKUATAN', romaji: 'chikara' },
      { japanese: 'へいわ', kanji: '平和', indonesian: 'PERDAMAIAN', romaji: 'heiwa' },
    ]
  }
];

export const INITIAL_INVENTORY: Item[] = [
  {
    id: 'w_bokuto',
    name: 'Bokuto',
    type: 'WEAPON',
    tier: 1,
    description: 'Pedang kayu latihan prajurit Ashigaru. Sederhana namun andal.',
  rarity: 'COMMON',
  attackBonus: 5,
    blockChance: 0,
    isEquipped: true,
  },
  {
    id: 's_tedate',
    name: 'Tedate Kayu',
    type: 'SHIELD',
    tier: 1,
    description: 'Perisai tangan kayu untuk menahan serangan panah dan tombak.',
  rarity: 'COMMON',
  defenseBonus: 5,
    blockChance: 3,
    isEquipped: true,
  },
  {
    id: 'c_yakuso_kecil',
    name: 'Yakuso Kecil',
    type: 'CONSUMABLE',
    tier: 1,
    description: 'Racikan tanaman obat sederhana. Memulihkan 30 HP.',
  rarity: 'COMMON',
  count: 3,
    effectType: 'HEAL',
    effectValue: 30,
    hpBonus: 30,
  },
];
